### PR TITLE
openaiapichatgpt: Initial Pull Request - Version 1.0.0

### PR DESCRIPTION
**Pull request by bentleymi**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [ y ] Testing of all the changes has been performed (for bug fixes / features)
- [ n/a ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [ y ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ y ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ y ] Verify all checks are passing.
- [ y ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ y ] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ y ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ n/a ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ y ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ n ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ n ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ n ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

Initial Release:  Version 1.0.0

Supported Actions:
get completion
get embeddings
get chat completion
get edits
test connectivity

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by aparekh-crest** [comment]
@bentleymi I have made changes as per our coding standards, few of the queries I need to ask,
1. Would it be fine if we change `min_phantom_version` to `6.0.2` in the app's json file as per our standard best practice?
2. This app uses `openai` and `numpy` libraries, could you please provide me library version you are using for this app? so that we can add those versions in the app's `requirement.txt` file?

**Comment by bentleymi** [comment]
I'm so glad you're helping with this.  I was dumbfounded by the requirements on checkin...Sure you can change the min phantom version but won't that make it so earlier versions can install it?I know it works on 5.x haven't tested 6.I grabbed the latest libraries.  I didn't even specify a version.  Thought soar took care of that on the backend.  Any of the latest versions should do.I hope that helps and thanks a ton again for your assistance!On Aug 17, 2023, at 12:19 PM, aparekh-crest ***@***.***> wrote:﻿
@bentleymi I have made changes as per our coding standards, few of the queries I need to ask,

Would it be fine if we change min_phantom_version to 6.0.2 in the app's json file as per our standard best practice?
This app uses openai and numpy libraries, could you please provide me library version you are using for this app? so that we can add those versions in the app's requirement.txt file?

**Comment by aparekh-crest** [comment]
Hi @bentleymi,
Currently, our legal team is checking the feasibility of this app as this is an AI tool we are implementing as part of the integration.
I will let you know as soon as I get an update.

**Comment by aparekh-crest** [comment]
Hi @bentleymi ,
This app is in review with the legal team for the dependencies, and we will proceed once we get the confirmation.

**Comment by aparekh-crest** [comment]
Closing this PR for now. We will keep you updated if there are any changes.

**Comment by bentleymi** [comment]
What is the problem?On Nov 21, 2023, at 7:52 AM, aparekh-crest ***@***.***> wrote:﻿
Closing this PR for now. We will keep you updated if there are any changes.

**Comment by aparekh-crest** [comment]
@bentleymi , due to some security reasons, our legal team is not allowing this submission for now, once we get some updates regarding this app we will let you know

**Comment by bentleymi** [comment]
Checking to see if there are any updates?  TIA!

**Pull request closed without merging**
